name: Build and publish Seed Seeker Plus

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get this repository
        uses: actions/checkout@v4
        with:
          path: wrapper

      - name: Get SHPD Seed Seeker
        uses: actions/checkout@v4
        with:
          repository: akhial/shpd-seed-seeker
          ref: main
          path: app

      - name: Add Secret Rooms + Artifacts
        run: python wrapper/apply-customisation.py app

      - name: Add Secret Room Locator
        run: python wrapper/upgrade-secret-locations.py app

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: latest

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: app/web/package-lock.json

      - name: Build WebAssembly
        working-directory: app
        run: ./scripts/build-web-wasm.sh

      - name: Install website dependencies
        working-directory: app/web
        run: npm ci

      - name: Build website
        working-directory: app/web
        run: npm run build -- --base "/shpd-seed-seeker-plus/"

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload finished website
        uses: actions/upload-pages-artifact@v3
        with:
          path: app/web/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Publish website
        id: deployment
        uses: actions/deploy-pages@v4
